import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/index.scss'
import Nav from '@/app/components/Nav'
import useDefaultUser from '@/app/hooks/useDefaultUser'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Flagsmith with Next.js',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const defaultUser = useDefaultUser()

  return (
    <html lang='en'>
      <body className={inter.className}>
        <Nav defaultUser={defaultUser} />
        {children}
      </body>
    </html>
  )
}
